# networks:
#     default:
#         name: ewg-data-chat
#         external: true
services:
    ewg-data-chat:
        container_name: ewg-data-chat
        build:
            context: ..
            dockerfile: infra/Dockerfile
        image: ewg-data-chat
        env_file:
            - .env
        volumes:
            - ../secrets:/secrets
            - ../input-datasets:/input-datasets
            - ../backend:/app/backend
            - ../chroma_index:/chroma_index
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS
            GCP_PROJECT: $GCP_PROJECT
            GCS_BUCKET_URI: ${GCS_BUCKET_URI}
            OPENAI_API_KEY: ${OPENAI_API_KEY}
        depends_on:
            - chromadb
    chromadb:
        image: chromadb/chroma:latest
        container_name: ewg-rag-chromadb
        ports:
            - 8000:8000
        volumes:
            - ./docker-volumes/chromadb:/chroma/chroma
        environment:
            - IS_PERSISTENT=TRUE
            - ANONYMIZED_TELEMETRY=FALSE
            - CHROMA_CORS_ALLOW_ORIGINS=["*"] # This is not recommended for production environments.
